'use client';

import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Bell, Calendar, Megaphone, ClipboardList, AlertCircle } from 'lucide-react';
import { getNotifications, markNotificationRead, markAllNotificationsRead } from '@/services/notifications-api';
import type { NotificationItem, NotificationType } from '@/types/notifications';
import { DASHBOARD_DATA_CHANGED_EVENT } from '@/lib/dashboard-events';

const POLL_INTERVAL_MS = 30_000;

const TYPE_ICON: Record<NotificationType, typeof Bell> = {
  event: Calendar,
  announcement: Megaphone,
  task: ClipboardList,
  alert: AlertCircle,
};

function timeAgo(iso: string): string {
  const minutes = Math.round((Date.now() - new Date(iso).getTime()) / 60_000);
  if (minutes < 1) return 'just now';
  if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.round(minutes / 60);
  if (hours < 24) return `${hours}h ago`;
  const days = Math.round(hours / 24);
  return `${days}d ago`;
}

/* Polls rather than pushing in real time — simple and good enough for a
   club-sized member count; see services/notifications-api.ts for the
   underlying GET /notifications. Also refetches immediately on
   DASHBOARD_DATA_CHANGED_EVENT so a notification generated by something you
   just did elsewhere (posting an announcement that tags someone, etc.)
   doesn't wait for the next poll to show up for them. */
export default function NotificationBell() {
  const router = useRouter();
  const [open, setOpen] = useState(false);
  const [notifications, setNotifications] = useState<NotificationItem[]>([]);
  const [loading, setLoading] = useState(true);
  const boxRef = useRef<HTMLDivElement>(null);

  function load() {
    const token = sessionStorage.getItem('token');
    if (!token) return;
    getNotifications(token)
      .then(setNotifications)
      .catch(() => {})
      .finally(() => setLoading(false));
  }

  useEffect(() => {
    load();
    const interval = setInterval(load, POLL_INTERVAL_MS);
    window.addEventListener(DASHBOARD_DATA_CHANGED_EVENT, load);
    return () => {
      clearInterval(interval);
      window.removeEventListener(DASHBOARD_DATA_CHANGED_EVENT, load);
    };
  }, []);

  useEffect(() => {
    function handleClickOutside(e: MouseEvent) {
      if (boxRef.current && !boxRef.current.contains(e.target as Node)) setOpen(false);
    }
    window.addEventListener('mousedown', handleClickOutside);
    return () => window.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const unreadCount = notifications.filter((n) => !n.isRead).length;

  async function handleMarkRead(notification: NotificationItem) {
    if (notification.isRead) return;
    setNotifications((prev) => prev.map((n) => (n.id === notification.id ? { ...n, isRead: true } : n)));
    const token = sessionStorage.getItem('token');
    if (!token) {
      router.push('/login');
      return;
    }
    try {
      await markNotificationRead(token, notification.id);
    } catch {
      setNotifications((prev) => prev.map((n) => (n.id === notification.id ? { ...n, isRead: false } : n)));
    }
  }

  async function handleMarkAllRead() {
    const previous = notifications;
    setNotifications((prev) => prev.map((n) => ({ ...n, isRead: true })));
    const token = sessionStorage.getItem('token');
    if (!token) {
      router.push('/login');
      return;
    }
    try {
      await markAllNotificationsRead(token);
    } catch {
      setNotifications(previous);
    }
  }

  return (
    <div ref={boxRef} className="relative">
      <button
        onClick={() => setOpen((prev) => !prev)}
        aria-label="Notifications"
        className="relative rounded-lg p-2 text-gray-500 transition-colors hover:bg-gray-100"
      >
        <Bell className="h-5 w-5" />
        {unreadCount > 0 && (
          <span className="absolute right-1.5 top-1.5 flex h-2 w-2 rounded-full bg-[#ED6672]" />
        )}
      </button>

      {open && (
        <div className="absolute right-0 top-full z-30 mt-2 w-80 overflow-hidden rounded-xl border border-gray-200 bg-white shadow-lg">
          <div className="flex items-center justify-between border-b border-gray-100 px-4 py-2.5">
            <h3 className="text-xs font-bold uppercase tracking-wide text-gray-500">Notifications</h3>
            {unreadCount > 0 && (
              <button
                onClick={handleMarkAllRead}
                className="text-xs font-bold text-[#3D6C94] transition-colors hover:text-[#2A4A63]"
              >
                Mark all read
              </button>
            )}
          </div>

          <div className="max-h-96 overflow-y-auto">
            {loading ? (
              <p className="px-4 py-6 text-center font-mono text-xs text-gray-400">Loading…</p>
            ) : notifications.length === 0 ? (
              <p className="px-4 py-6 text-center font-mono text-xs text-gray-400">You're all caught up.</p>
            ) : (
              <div className="divide-y divide-gray-100">
                {notifications.map((n) => {
                  const Icon = TYPE_ICON[n.type];
                  return (
                    <button
                      key={n.id}
                      onClick={() => handleMarkRead(n)}
                      className={`flex w-full items-start gap-2.5 px-4 py-2.5 text-left transition-colors hover:bg-gray-50 ${
                        n.isRead ? '' : 'bg-[#B1C9DC]/10'
                      }`}
                    >
                      <span className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-gray-100">
                        <Icon className="h-3.5 w-3.5 text-[#3D6C94]" />
                      </span>
                      <span className="min-w-0 flex-1">
                        <span className={`block truncate text-sm ${n.isRead ? 'text-gray-600' : 'font-bold text-gray-900'}`}>
                          {n.title}
                        </span>
                        {n.message && (
                          <span className="block truncate text-xs text-gray-500">{n.message}</span>
                        )}
                        <span className="block font-mono text-[10px] text-gray-400">{timeAgo(n.createdAt)}</span>
                      </span>
                      {!n.isRead && <span className="mt-1.5 h-1.5 w-1.5 shrink-0 rounded-full bg-[#ED6672]" />}
                    </button>
                  );
                })}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
